// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7PHd-jWMClwaPdk4vnCqEaN-McnA2GZw',
    appId: '1:266952133671:web:001d892ddf411a26aed202',
    messagingSenderId: '266952133671',
    projectId: 'latihan-auth-c298f',
    authDomain: 'latihan-auth-c298f.firebaseapp.com',
    storageBucket: 'latihan-auth-c298f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9nBTohpZxolTblEdx2L8VCOWKh_x22lE',
    appId: '1:266952133671:android:00aab9585fb12979aed202',
    messagingSenderId: '266952133671',
    projectId: 'latihan-auth-c298f',
    storageBucket: 'latihan-auth-c298f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRtdEg45Ubh11kJGoU-2REeEiwhV81SNg',
    appId: '1:266952133671:ios:f31103410833898daed202',
    messagingSenderId: '266952133671',
    projectId: 'latihan-auth-c298f',
    storageBucket: 'latihan-auth-c298f.appspot.com',
    iosBundleId: 'com.example.sanberappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRtdEg45Ubh11kJGoU-2REeEiwhV81SNg',
    appId: '1:266952133671:ios:61af52b31f8eaecbaed202',
    messagingSenderId: '266952133671',
    projectId: 'latihan-auth-c298f',
    storageBucket: 'latihan-auth-c298f.appspot.com',
    iosBundleId: 'com.example.sanberappflutter.RunnerTests',
  );
}
